try {
  console.log(naoExisto);
} catch (err) {
  console.error("naoExisto n√£o existe");
}